apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: md.dotglitch.dev-ingress
spec:
  entryPoints:
   - web
  routes:
    - match: Host(`md.dotglitch.dev`)
      kind: Rule
      services:
      - name: md-dotglitch-server
        port: 80

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: md.dotglitch.dev-secure-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`md.dotglitch.dev`)
      services:
        - name: md-dotglitch-server
          port: 80
  tls:
    secretName: md.dotglitch.dev-tls

---

apiVersion: v1
kind: Service
metadata:
  name: md-dotglitch-server
spec:
  selector:
    app: md-dotglitch-server
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-dotglitch-server
spec:
  selector:
    matchLabels:
      app: md-dotglitch-server
  replicas: 1
  template:
    metadata:
      labels:
        app: md-dotglitch-server
    spec:
      containers:
      - name: dotglitch
        image: harbor.dotglitch.dev/library/md-dotglitch:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harbor-key

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: md.dotglitch.dev
spec:
  commonName: md.dotglitch.dev
  dnsNames:
    - md.dotglitch.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: md.dotglitch.dev-tls


