name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Compile Electron App
        uses: x6Pnda/action-electron-compiler@v1
        with:
            github_token: ${{ secrets.github_token }}
            release: ${{ startsWith(github.ref, 'refs/tags/v') }}
            package_manager: NPM
