name: Angular Build

# {1}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    name: Angular Build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {3}
      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # {4}
      - name: Install dependencies
        run: npm ci
      # {5}
    #   - name: Run tests
        # run: npm run test:ci
      # {6}
      - name: Build
        run: npm run build:app
      - name: PWD
        run: pwd
      - name: LS 1
        run: ls .
      - name: LS 2
        run: ls ./dist
      - name: LS 3
        run: ls ./dist/stackedit
      - name: LS 4
        run: ls ./dist/stackedit/browser
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist repository
          path: './dist/stackedit/browser'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
